# Jekyll configuration

name: Nicolas Monnier
description: Ihr Politiker der Linken Alternative!

# url is currently only used only for the RSS feed in feed.xml
url: https://nicolas-monnier.eynet.xyz

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''
## default date_format
date_format:
  title: "%B-%-d-%Y"
  archive: "%b %d"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "de"

permalink: /:year/:month/:day/:title.html

pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate-v2']

exclude: ['README.md', 'LICENSE', "*.bak"]
